### ISSUE TITLE
Datatables Export PDF

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#10]
The export PDF option for the Datatables doesn't work and gives the error:
```
 PHPExcel_Writer_Exception
 Unable to load PDF Rendering library
```

**Comment by brandonjank** [comment]
Still tracking this one down, may need to use the other library as DomPDF is installed properly and working :(

**Comment by brandonjank** [comment]
Using snappy now, see pull requests #69 #70 and #71

**Comment by brandonjank** [comment]
@brec9824 @Cyberzoid1 How do you feel about nixing PDF support. We having working csv/excel support. If they want a PDF they can use the built-in Print to PDF tool on every windows and mac computer. As it is, the amount of packages and configuration for generating PDFs is very large, several hundred megabytes. :(

**Comment by brec9824** [comment]
@brandonjank I say just remove PDF support. It was never a requirement and there are plenty of other options available to the user anyway.

**Comment by Cyberzoid1** [comment]
I would say if they want pdf they can export to pdf via excel
In support to drop pdf

**Comment by brandonjank** [comment]
PR #104 should close this issue when merged.
