### ISSUE TITLE
Datatables search gives error

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#11]
Entering any letter into the search field for Datatables gives an error message: 
![error1](https://user-images.githubusercontent.com/16866862/30350508-c604e4b8-97cb-11e7-83f0-44de30e5e825.JPG)

**Comment by brandonjank** [comment]
Fixed in branch issue-11.

**Comment by brandonjank** [comment]
#13

**Comment by brandonjank** [comment]
Moved to Done on the Scrum board and closed.

**Comment by brandonjank** [comment]
Issue resolved, closing.
