### ISSUE TITLE
Inform user of outdated device image

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#20]
If the device image has not been updated for a certain amount of time. Then the dashboards device image should display to the user that the image is old. This way the user will be able to tell when viewing a live image rather then an old image.

**Comment by Cyberzoid1** [comment]
I havent voiced this but I was thinking of adding a timestamp to the bottom of the image.

I have not looked into what it would take to implement this. If implemented, I think it would be best done on the device side.

**Comment by brec9824** [comment]
Closed, duplicate issues. More recent issue is #39

**Comment by brec9824** [comment]
Reopening this issue is specifically for displaying on the image that the image is out of date.

**Comment by brec9824** [comment]
Closing, added with pull request #99
