### ISSUE TITLE
Identify new devices

### ISSUE THREAD

**Issue by Cyberzoid1** [uidaho/smartsettia#36]
When a new device is added, its nearly impossible to tell  which new device is which.
![image](https://user-images.githubusercontent.com/18319510/30785138-89b811d4-a116-11e7-9c7d-b122f56d6351.png)

Some possible solutions
Append date time to device name. `New Device 9-24 1055`
Append last few digits of uuid to name `New Device cx9vswd8`
Add column with date added
Add column with part of uuid
Come up with a way for the device to specify its own name until overwritten by server.

**Comment by brec9824** [comment]
Probably appending the date time to the device name when the device is added to the database. I think that would be enough to identify the device.

**Comment by Cyberzoid1** [comment]
I think this line 140 is the key to add the id number like we discussed earlier today
https://github.com/uidaho/smartsettia/blob/3f7b1fe55ba5d81d8a8e1ce80a09fd93c1ea092b/app/Http/Controllers/ApiController.php#L138-L142

If the id is generated by the `$device = new Device;`
then we could pull the ID and concatenate it to the name right?

**Comment by Cyberzoid1** [comment]
Thinking something like this
```php
$device->name = 'New Device'. " - ". $device->id;
```
However I dont think id is generated at this point

**Comment by brandonjank** [comment]
The created time and id are in the same table, why are we duplicating this information?

**Comment by brec9824** [comment]
Closed. Brandon is right this isn't needed since this will just duplicate data.
