### ISSUE TITLE
Long device names cause button format issue on dashboard

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#37]
For example "Functional Test Device Name" causes the device buttons on the dashboard to wrap onto a second line. Possible solution is after a certain length the name gets cut off and replaced by trailing periods. This way the user knows the device name has been cutoff because of length.

**Comment by brandonjank** [comment]
@brec9824 has this been addressed? Could you make a quick screenshot of the problem if it still does? Thanks!

**Comment by brec9824** [comment]
Probably just need to limit the max length of names to be shorter but I thought it looks weird when the buttons start line breaking. The issue really comes about when it is viewed on a small screen like a phone since it requires scrolling to see the buttons.

Here is a couple of images with different screen widths:
![long device name](https://user-images.githubusercontent.com/16866862/32536811-d5880918-c414-11e7-8826-68f19bfa40f8.JPG)
![long device name2](https://user-images.githubusercontent.com/16866862/32536934-5dbfe1b6-c415-11e7-967e-b24223602a9e.JPG)
![long device name3](https://user-images.githubusercontent.com/16866862/32536937-6325a7f8-c415-11e7-9cf7-d5af623a102d.JPG)

**Comment by brandonjank** [comment]
I believe we addressed this by limiting the size of device/location/site names with validation. Closing.
