### ISSUE TITLE
Logout error

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#38]
Logging out on while on the edit user or the edit device view causes an error and you aren't logged out. 
![error](https://user-images.githubusercontent.com/16866862/30840317-6bf6f5fa-a22b-11e7-9363-db143158ee43.JPG)

**Comment by brec9824** [comment]
Just checked and this issue is resolved.

**Comment by brec9824** [comment]
Issue is back but when logging out from any device.show page. The URL being displayed when recieving the error is `https://smartsettia.com/device/logout`.

**Comment by brec9824** [comment]
Issue is back but when logging out from any device.show page. The URL being displayed when recieving the error is `https://smartsettia.com/device/logout`.

**Comment by brandonjank** [comment]
This has been addressed in PR #105 and can be closed when it is merged.
