### ISSUE TITLE
Alert the user when device image is stale

### ISSUE THREAD

**Issue by brandonjank** [uidaho/smartsettia#39]
When the image has not been updated by the client in more than say 10 minutes, we should add an element that has an alert to the user.

**Comment by brandonjank** [comment]
possibly send a text message?

**Comment by Cyberzoid1** [comment]
Possibly needs to be brought up in the next meeting on how to handle different 'errors'
for instance when i send `Err1: no webcam." or "Err2: temp sensor disconnect"
Are these warnable errors or errors notified only once, or errors that just down up on the website but not pushed out.

We could also have say 2 levels of notifications
* All errors
* Critical errors

**Comment by brec9824** [comment]
Closing, since the image alert is already added and user notifications will only be sent based on device created error messages.
