### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by Cyberzoid1** [uidaho/smartsettia#40]
Better more user friendly 404 page
![image](https://user-images.githubusercontent.com/18319510/30841566-ff978aa8-a231-11e7-8832-64550660350c.png)

**Comment by brandonjank** [comment]
The site is in debug mode, the pretty 404 route or any other pretty errors will not be shown.

**Comment by Cyberzoid1** [comment]
Ah
You can close this then.
Or keep it up for some reminder

**Comment by brandonjank** [comment]
Site has been put into production mode which shows pretty 404 errors. Closing.
