### ISSUE TITLE
Device image memory size is to large

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#54]
Currently the image size being downloaded from the server is jumping from around 50kbs to 450kbs. Looks like image saving should resize the image first before saving to have a consistent size image. 
Example: 
`// open and resize an image file`
`$img = Image::make('public/foo.jpg')->resize(300, 200);`

`// save file as jpg with medium quality`
`$img->save('public/bar.jpg', 60);`

**Comment by Cyberzoid1** [comment]
I was going to look into that .
On my pi the picture is 504kb which was taking about 4-5 seconds to upload on my connection.
I was going to look into options to resize or compress the picture down to around 100k. maybe even 50k

What are you referring to too large?  data size or resolution size?

**Comment by Cyberzoid1** [comment]
Preferably this should be done on the pi as it directly affects upload time, thus our update rate.
We would want to math this out so that uploading the picture takes under 1 second. 

@brandonjank What typical up speeds can we expect in the greenhouse?

**Comment by brec9824** [comment]
Size I was talking about was data size but using intervention.image on the server requires resizing and setting the quality. Which would effect the data size. You are probably right and it should be done on the PI and probably around 50-100kbs would be good. We can try to 50kbs and see how it looks and if it is to pixelated we can just keep going up till it looks good.

**Comment by brandonjank** [comment]
At 95 compression images are about 100 kilobytes.

**Comment by brec9824** [comment]
Fixed in merge #55. Closing
