### ISSUE TITLE
Editing devices on the dashboard is broken

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#57]
Attempting to edit a device on the dashboard does nothing because of errors.
![error](https://user-images.githubusercontent.com/16866862/31057879-cf8bcbb4-a69e-11e7-9456-f3b56a1259de.JPG)

**Comment by brec9824** [comment]
Okay, I believe the issue above is because I have the URL hard coded and my local environment is not smarsettia.com. But on the actual smartsettia webpage I receive
![error 2](https://user-images.githubusercontent.com/16866862/31057900-4e2c5ae2-a69f-11e7-8a48-5ecdec774817.JPG)
 a different error when trying to edit a device.

**Comment by brandonjank** [comment]
youre posting to the view method of the controller?
![image](https://user-images.githubusercontent.com/784730/31058023-d5faf1e8-a6a1-11e7-83f4-dc74311a886a.png)

**Comment by brandonjank** [comment]
After looking at the modal edit code.. this should have been done much differently. We shouldnt have two separate edit templates. Additionally, joins should never be done in laravel by hand that is what eloquent relationships are for.  See https://laravel.com/docs/5.5/eloquent-relationships
@brec9824 please call me on discord for more info
