### ISSUE TITLE
Redirect registration to dashboard

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#6]
Upon registering for an account you are redirected to the home page. You should probably be redirected to the dashboard.

**Comment by backburn** [comment]
the login redirect is set to /dashboard as per:
smartsettia/app/Http/Controllers/Auth/LoginController.php

I was not able to recreate this issue using master on my local workstation. I'll get the main site back up here shortly to test again.

**Comment by backburn** [comment]
My apologies, I read registration as login! The after registration redirect is set to /home in C:\WTServer\WWW\smartsettia\app\Http\Controllers\Auth\RegisterController.php 

You want to fix?

**Comment by backburn** [comment]
Or  maybe we can use this issue as a test when we get the dev environment setup Thursday?

**Comment by brec9824** [comment]
I just added this as I thought being redirected to the home screen seemed kind of pointless. Since a logged in user has nothing to do on the home view unless they want to read about what they just signed up for.

**Comment by brec9824** [comment]
Fixed with commit 35d2cf0
