### ISSUE TITLE
Device cover_command always NULL

### ISSUE THREAD

**Issue by Cyberzoid1** [uidaho/smartsettia#62]
Always getting back NULL or "none" on my end

![image](https://user-images.githubusercontent.com/18319510/31322680-4311d4ae-ac51-11e7-91ed-bc9227fcc3bf.png)

**Comment by brec9824** [comment]
It is because in the database migration cover_command is nullable and there is no default. We should probably change the column to not be nullable and have a default of like lock or something.

**Comment by Cyberzoid1** [comment]
it shouldnt matter.
if you absorb the state the device gives you when it next connects then that will be the state you use.
So I would agree locked would be good until the device gives you its first update.

This is also important for synchronization. Say the device was offline and it experienced a state change(scheduled). At that point the server would synchronize by reading the device status then send any commands
