### ISSUE TITLE
Changelog for users

### ISSUE THREAD

**Issue by Cyberzoid1** [uidaho/smartsettia#85]
Simple change-log report to advertise new functionality of the site as we add features.

This will let the users know whats new and help provide feedback.

Currently there is no way for users to know whats new and may expect functionality so not be working even though it may have been finish

![image](https://user-images.githubusercontent.com/18319510/31647126-25402848-b2bb-11e7-857c-66c74e4dd317.png)

**Comment by Cyberzoid1** [comment]
The change log does not have to be dynamic. just statically set as we are developing, then removed when we are done. 
Only needs to show the last few changes/features or the last few days worth.

**Comment by brec9824** [comment]
Closing, since we are about to move to release and we don't currently have any active users.
