### ISSUE TITLE
Device status on model page

### ISSUE THREAD

**Issue by Cyberzoid1** [uidaho/smartsettia#86]
## Current Behavior
Does not show status of the device. It could be online, or off line. When did it go offline

## Possible Solution
If onilne show green online
if offline for more than a specified time (1 min) show either timedate it was last seen or `last seen x <timeunits> ago`

![image](https://user-images.githubusercontent.com/18319510/31647384-b0a15c08-b2bc-11e7-9456-45ca47972027.png)

**Comment by brec9824** [comment]
Closing, added with pull request #99
