### ISSUE TITLE
Enlarge device image when clicked on Device.show

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#89]
## Expected Behavior

Clicking the device's image on the device.show view will enlarge the image for viewing. Similar to how clicking on a image on the dashboard causes it to be enlarged.
## Current Behavior

Currently the image is tiny and would be nice to be able to view the device's image on the device.show page.
## Possible Solution

Mentioned above and could be easily copied over using the code written for pull request #53

**Comment by brandonjank** [comment]
Should be fixed in PR #114

**Comment by brec9824** [comment]
Closing, fixed in PR #114
