### ISSUE TITLE
Is unlock icon available for only selective user who has access to the unit?

### ISSUE THREAD

**Issue by devsgr** [uidaho/smartsettia#91]
Is unlock icon available for only selective user who has access to the unit?

**Comment by brec9824** [comment]
Currently anyone who registers can use the device commands unlock, lock, open, and close. We still need to implement the sites authorization rules to limit who can do what.

**Comment by brandonjank** [comment]
@devsgr We plan on implementing access policy last, once all the features are in place. If you have any requirements for who can do what we'd love to hear them so we can get them in the access policy plan.
