### ISSUE TITLE
Editing a unit causes error

### ISSUE THREAD

**Issue by brandonjank** [uidaho/smartsettia#92]
See image
![image](https://user-images.githubusercontent.com/784730/31911179-a794cca2-b7f4-11e7-91fb-0699aa6b42e2.png)

**Comment by brec9824** [comment]
@brandonjank This issue is caused by line 189 of DeviceController ```php $this->RemoveUnusedSiteLoc();``` the function got deleted in your last pull request. This line can just be removed. I hoping to have the dashboard re-fracture completed today or tomorrow and I have this removed in my branch.

**Comment by brandonjank** [comment]
@brec9824 sounds good, just put this here to remind me to fix it when i get home from work. I'll leave it be, just add this issue # to your PR if you get to it.

**Comment by brec9824** [comment]
Closing, fixed in pull request #96
