### ISSUE TITLE
Show views do not display data on small screens

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#95]
## Expected Behavior

Users with small screens should be able to see the views in a similar fashion to how it would look on a large screen.

## Current Behavior

On the show views if the screen is <= 900 pixels the data becomes hidden. Here is a picture: 
![bug](https://user-images.githubusercontent.com/16866862/31979448-aa96e612-b8fb-11e7-9743-85850d374c42.JPG)

## Steps to Reproduce (for bugs)

1. Use a small screen or resize your browser while on one of the show views

**Comment by brandonjank** [comment]
The hidden-xs hidden-sm classes could be causing it like on sensor show: 
![image](https://user-images.githubusercontent.com/784730/31982041-70ca9f5e-b90b-11e7-8ad3-aaca274b2b19.png)

**Comment by brec9824** [comment]
Yeah the hidden classes are the issue. With the hidden classes removed allot of the text is going off the screen. So we will probably need to make some changes to how it is being displayed on smaller screens.

**Comment by brandonjank** [comment]
I'm going to change the template for how sections of the site are displayed. The panel type is what is hosing us with small responsive layouts. Expect a face-lift PR next week once we get all the CRUD done.

**Comment by brandonjank** [comment]
Should be fixed in PR #106

**Comment by brec9824** [comment]
Closing, fixed as mentioned above.
